language: python
python:
  - "3.6"
  - "3.7"
# command to run tests
script: 
  - echo "skipping tests"
  #- pytest --cov=recommender tests/ --cov-report=html
branches:
 only:
  - dev
after_success:
  - coveralls


